config/routes.rb
Rails.application.routes.draw do
    
  
  devise_for :users
    
    
     resources :listings do
         
     resources :orders, only: [:new, :create] 
    end
    
    root 'listings#index'
    
    get 'seller' => "listings#seller"
    
    get 'seller' => "listings#seller"
    get 'sales' => "orders#sales"
    get 'purchases' => "orders#purchases"
    
  get 'pages/about'

  get 'pages/contact'

  get 'pages/privacy'

  get 'pages/gaqs'

 
  
    
end

app/models/listing.rb
class Listing < ActiveRecord::Base
    
    validates :name, :description, :price, :image, presence: true
    validates :price, numericality: { greater_than: 0 }
    
    belongs_to :user
end

app/models/order.rb
class Order < ActiveRecord::Base
    validates :name, :address, :county, :postcode, presence: true
    
    belongs_to :listing
    
    belongs_to :buyer, class_name: "User"
    belongs_to :seller, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    
     validates :name, presence: true
    
    has_many :listings, dependent: :destroy
    
    has_many :sales, class_name: "Order", foreign_key: "seller_id"
    has_many :purchases, class_name: "Order", foreign_key: "buyer_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
      
      devise_parameter_sanitizer.for(:account_update) << :name
      
      
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, only: [:seller, :new, :create, :edit, :update, :destroy]
    before_action :check_user, only: [:edit, :update, :destroy]
   
    def seller
        @listings = Listing.where(user: current_user).order("created_at DESC")
    end
    
  def index
      @listings = Listing.all.order('created_at desc')
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
      @listing.user_id = current_user.id
    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
        params.require(:listing).permit(:name, :description, :price, :image)
    end
    
    def check_user
        if current_user != @listing.user
            redirect_to root_path, alert:"Sorry, this listing belongs to someone else"
    end
    end
    
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    
  before_action :set_order, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!

    def sales
        @orders = Order.all.where(seller: current_user).order("created_at DESC")
    end
    
    def purchases
        @orders = Order.all.where(buyer: current_user).order("created_at DESC")
    end
    
  def index
    @orders = Order.all
  end

  # GET /orders/new
  def new
    @order = Order.new
      @listing = Listing.find(params[:listing_id])
  end



  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
      @listing = Listing.find(params[:listing_id])
      @seller = @listing.user
      @order.buyer_id = current_user.id
      @order.listing_id = @listing.id
      @order.seller_id = @seller.id
      
    respond_to do |format|
      if @order.save
        format.html { redirect_to root_url, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :address, :county, :postcode)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def privacy
  end

  def gaqs
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
<footer class="footer">
<small>
Copyright © <a href="http://www.microbites.co.uk">Store Rangers</a>
by <a href="http://www.ckwe.org">Richard Jatto</a>
</small>
<nav>
<ul>
    <li><%= link_to "About", pages_about_path %></li>
    <li><%= link_to "Contact", pages_contact_path %></li>
    <li><%= link_to "Privacy", pages_privacy_path %></li>
    <li><%= link_to "FAGS", pages_gaqs_path %></li>
</ul>
</nav>
</footer>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
        <li><%= link_to 'Store Rangers', root_path, class: "navbar-brand", id: "logo" %></li>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
         <li><%= link_to 'Shop', root_path %></li>
        <li><%= link_to 'About', pages_about_path %></li>
        <li><%= link_to 'Contact', pages_contact_path %></li>
        
      </ul>
     
      <ul class="nav navbar-nav navbar-right">
           <% if user_signed_in? %>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Seller Account <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'List-A-Product', new_listing_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Manage Listing', seller_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Sales History', sales_path %></li>
              
          </ul>
        </li>
      
         <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Purchase History', purchases_path %></li>
              <li role="separator" class="divider"></li>
           <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
               <li role="separator" class="divider"></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
    
          <% else %>
          <li><%= link_to 'Register', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
          <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store-Rangers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "https://js.stripe.com/v2" %>
  <%= csrf_meta_tags %>
    <%= tag :meta, :name => "stripe-key", :content => ENV["STRIPE_PUBLIC_KEY"] %>
</head>
    
    
<body>
<%= render '/layouts/navbar' %>
    <div class="container">
    
    <% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>
        
<%= yield %>

        
        <%= render 'layouts/footer' %>
</div>
    
</body>
</html>

app/views/listings/_form.html.erb
<%= form_for(@listing, html: { multipart: true }) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation alert alert-danger alert-dismissible" role="alert">
         <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h4>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
      <%= f.text_field :name, class: "form-control" %>
  </div>
    <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
    <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price , class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :image %><br>
      <%= f.text_field :image , class: "form-control"%>
  </div>
    <div class="form-group">
    <%= f.submit  class: "btn btn-danger" %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<div class="jumbotron">
<!--<h1>Quality items..</h1>

<h3>@ amazing Prices</h3>-->

</div>

<div class="center">

<div class="row">
  <% @listings.each do |listing| %>
  <div class="col-md-3">

    <div class="thumbnail">
       
        <%= link_to (image_tag listing.image), listing %>
        <div class="caption">
            <h4><%= listing.name %></h4>
            <p><%= truncate(listing.description, length: 50) %></p>
        <p><%= number_to_currency listing.price, unit:'£' %></p>
          <p><%= "Sold By: #{listing.user.name}" %></p>
       
            
       </div>
     </div>  
  </div>
 
  <% end %>
     
 </div>
</div>

<p><%= image_tag "credit-card.png", :width => 400, :height => 100 %></p>

app/views/listings/new.html.erb
<div class="log-in">
<div class="panel panel-primary">
<div class="center panel-heading">


<h1>New Listing</h1>
    </div>
    
    <div class="panel-body">
<%= render 'form' %>

<%= link_to 'Back', listings_path, class: "btn btn-link" %>
</div>
    </div>
    </div>

app/views/listings/seller.html.erb
    
      <table class="table table-striped table-bordered">
    <thead>
          <tr>
            <th class="center success">Image</th>
            <th class="center success">Name</th>
            <th class="center success">Description</th>
            <th class="center success">Price</th>
               <th class="center success">Seller</th>
              <th class="center success">Manage</th>
          </tr>
        </thead>

          <tbody>
                <% @listings.each do |listing| %>
          <tr>
            <td><%= image_tag listing.image, :width => 100, :height => 100  %></td>
              <td><%= listing.name %></td>
            <td><%= listing.description %></td>
            <td><%= number_to_currency listing.price, unit:'£' %></td>
            <td><%= listing.user.name %></td>
              <td>
            <div class="btn-group">
  <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Action <span class="caret"></span>
    </button>
  
  <ul class="dropdown-menu">
    <li><%= link_to 'Edit', edit_listing_path(listing), class: "btn btn-link" %></li>
      <li role="separator" class="divider"></li>
    <li> <%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></li>
      <li role="separator" class="divider"></li>
    <li><%= link_to 'Show', listing, class: "btn btn-link" %></li>
      </ul>
    </div>
    </td>
    </tr>
    <% end %>
    </tbody>
    </table>
        
    

app/views/listings/show.html.erb
<div class="row">

<div class="col-md-6">
	<div class="thumbnail">
	<%= image_tag @listing.image %>
</div>
</div>

<div class="col-md-6">
    <h3> <%= @listing.name %></h3>
<p> <%= number_to_currency @listing.price, unit: '£' %></p>
<p> <%=  @listing.description %></p>
    
    <div class="center">
        <%= link_to 'Buy Now', new_listing_order_path(@listing), class: "btn btn-success" %>
</div>
</div>
</div>

<% if current_user == @listing.user %>


<%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-link" %> 
 

<% end %>
<%= link_to 'Back', listings_path, class: "btn btn-link" %>
 <p><%= image_tag "credit-card.png", :width => 400, :height => 100 %></p>

app/views/orders/_form.html.erb
<div class="row">
<div class="col-md-4">
    <div class="thumnail">
        <%= image_tag @listing.image, :width => 300, :height => 300 %>
    </div>
    <h3><%= @listing.name %></h3>
    <h4><%= number_to_currency(@listing.price, unit: '£') %></h4>
    </div>
    
    <div class="col-md-8">
    

<%= form_for([@listing, @order]) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation alert alert-danger alert-dismissible" role="alert">
         <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4><%= pluralize(@order.errors.count, "error") %> prohibited this listing from being saved:</h4>

      <ul>
          <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  


    
    
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :county %><br>
    <%= f.text_field :county, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :postcode %><br>
    <%= f.text_field :postcode, class:"form-control" %>
  </div>
<div class="form-group">
    <div class="row">
        <div class="col-md-8">
            <%= label_tag :card_number, "Credit Card Number" %>
        <%= text_field_tag :card_number, nil, {:name => nil, :'data_stripe' => "number", class: "form-control"} %>
    
        </div> 
            <div class="col-md-4">
                
            <%= label_tag :card_code, "CVC" %>
            <%= text_field_tag :card_code, nil, {:name => nil, :'data_stripe' => "cvc", class: "form-control"} %>
            </div>
            </div>

           </div>
       <div class="form-group">
           <%= label_tag nil, "Expiration Date" %>
        <div class="row">
    <div class="col-md-3">
    <%= select_month nil, { use_two_digit_numbers: true }, {:name => nil, :'data_stripe' => "exp-month", class: "form-control"} %>
    </div>
    <div class="col-md-3">
       <%= select_year nil, { start_year: Date.today.year, end_year: Date.today.year+10 }, {:name => nil, :'data_stripe' => "exp-year", class: "form-control"} %>
            </div>
</div>
</div>
  <div class="form-group">
      <%= f.submit "complete order", class: "btn btn-success" %>
  </div>
 
<% end %>
        <p><%= image_tag "credit-card.png", :width => 400, :height => 100 %></p>
</div>
</div>

app/views/orders/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', listing_orders_path %>

app/views/orders/purchases.html.erb
<div class="center">
<h2>Your Purchase History</h2>
</div>
    
      <table class="table table-striped table-bordered">
    <thead>
          <tr class="center success">
            <th>Image</th>
            <th>Item</th>
            <th>Price</th>
            <th>Seller</th>
               <th>Date Sold</th>
              
          </tr>
        </thead>

          <tbody>
              <% @orders.each do |order| %>
          <tr>
              <td class="center"><%= image_tag order.listing.image, :width => 100, :height => 100  %></td>
              <td class="center"><%= order.listing.name %></td>
            
              <td class="center"><%= number_to_currency(order.listing.price, unit:'£') %></td>
              <td class="center"><%= order.seller.name %></td>
              <td class="center"><%= order.created_at.strftime("%B %-d, %Y") %></td>
              </tr>
              <% end %>
    </tbody>
    </table>
        
    

app/views/orders/sales.html.erb
<div class="center">
<h2>Your Sales History</h2>
</div>
    
      <table class="table table-striped table-bordered">
    <thead>
          <tr class="center success">
            <th>Image</th>
            <th>Item</th>
            <th>Price</th>
            <th>Customer</th>
               <th>Date Sold</th>
              
          </tr>
        </thead>

          <tbody>
              <% @orders.each do |order| %>
          <tr>
              <td><%= image_tag order.listing.image, :width => 100, :height => 100  %></td>
              <td><%= order.listing.name %></td>
            
              <td><%= number_to_currency(order.listing.price, unit:'£') %></td>
              <td><%= order.buyer.name %></td>
              <td><%= order.created_at.strftime("%B %-d, %Y") %></td>
              </tr>
              <% end %>
    </tbody>
    </table>
        
    

app/views/pages/about.html.erb
<div class="log-in">
<div class="panel panel-primary">
  <div class="panel-heading">
    
    <h1>About Us</h1>
    </div>
  <div class="panel-body">Panel Content


<p>Store-Rangers is an online store where everyone can sell their product(s) without the drama of owning or paying for a website</p>
<hr>
</div>
</div>
    </div>

app/views/pages/contact.html.erb
<div class="log-in">
<div class="panel panel-primary">
  <div class="panel-heading">
    <h2>Contact us for more info</h2>
    
    </div>
  <div class="panel-body">Panel Content


<p>Store-Rangers is an online store where everyone can sell their product(s) without the drama of owning or paying for a website</p>
    <address>
Email: info@global-market.com <br>
Telephone: 02036998787 <br>
Website: http://www.microbites.co.uk<br><hr>
</address>  
<hr>
</div>
</div>
    </div>

app/views/pages/gaqs.html.erb
<h1>Pages#gaqs</h1>
<p>Find me in app/views/pages/gaqs.html.erb</p>

app/views/pages/privacy.html.erb
<h1>Pages#privacy</h1>
<p>Find me in app/views/pages/privacy.html.erb</p>